server:
  port: 8081

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  database:
    driverClassName: org.postgresql.Driver
  datasource:
    url: jdbc:postgresql://localhost:5432/adm
    username: adm
    password: adm