server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/adm
    username: adm
    password: adm
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    baseline-on-migrate: true

schedulers:
  reset-limits: "0 0 0 * * *"